-- Insert sample data for testing
INSERT INTO providers (id, name, location, procedure, priceRange, languages, tags, availability, contact, services, reviews, mapEmbedUrl)
VALUES
('1', 'Istanbul Hair Clinic', '{"city": "Istanbul", "country": "Turkey", "address": "Barbaros Blv. No:145, Besiktas"}', 'Hair Transplant', '$2,500 - $4,000', ARRAY['English', 'Turkish', 'Arabic'], ARRAY['Accredited', 'Airport pickup', 'Accommodation'], 'Next 2 weeks', '{"phone": "+90 555 123 4567", "email": "info@istanbulhairclinic.com", "website": "https://www.istanbulhairclinic.com"}', ARRAY['FUE Hair Transplant', 'DHI Hair Transplant', 'Beard Transplant'], '[{"source": "Trustpilot", "url": "https://www.trustpilot.com/review/istanbulhairclinic.com", "score": "4.8/5"}, {"source": "Google", "url": "https://maps.app.goo.gl/example1", "score": "4.7/5"}]', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3008.7000000000005!2d29.00000000000000!3d41.00000000000000!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMznCsDU5JzU5LjkiTiAyOcKwMDAnMDAuMCJF!5e0!3m2!1sen!2sus!4v1678901234567!5m2!1sen!2sus'),

('2', 'Bangkok Dental Center', '{"city": "Bangkok", "country": "Thailand", "address": "123 Sukhumvit Road, Bangkok"}', 'Dental Implants', '$800 - $1,500', ARRAY['English', 'Thai'], ARRAY['ISO Certified', 'Airport pickup'], 'Within 1 month', '{"phone": "+66 2 123 4567", "email": "info@bangkokdental.com", "website": "https://www.bangkokdental.com"}', ARRAY['Dental Implants', 'Veneers', 'Teeth Whitening'], '[{"source": "Google", "url": "https://maps.app.goo.gl/example2", "score": "4.6/5"}]', null),

('3', 'Seoul Cosmetic Surgery', '{"city": "Seoul", "country": "South Korea", "address": "456 Gangnam-gu, Seoul"}', 'Cosmetic Surgery', '$3,000 - $8,000', ARRAY['English', 'Korean'], ARRAY['JCI Accredited', 'Translator service'], 'Flexible', '{"phone": "+82 2 123 4567", "email": "info@seoulcosmetic.com", "website": "https://www.seoulcosmetic.com"}', ARRAY['Rhinoplasty', 'Facelift', 'Breast Augmentation'], '[{"source": "RealSelf", "url": "https://www.realself.com/example", "score": "4.9/5"}]', null),

('4', 'Mumbai Eye Hospital', '{"city": "Mumbai", "country": "India", "address": "789 Marine Drive, Mumbai"}', 'Eye Surgery (LASIK)', '$500 - $1,200', ARRAY['English', 'Hindi'], ARRAY['NABH Accredited', 'Follow-up care'], 'Next 2 weeks', '{"phone": "+91 22 123 4567", "email": "info@mumbaieye.com", "website": "https://www.mumbaieye.com"}', ARRAY['LASIK', 'Cataract Surgery', 'Retinal Surgery'], '[{"source": "Practo", "url": "https://www.practo.com/example", "score": "4.7/5"}]', null),

('5', 'Tijuana Medical Center', '{"city": "Tijuana", "country": "Mexico", "address": "321 Avenida Revolución, Tijuana"}', 'Weight Loss Surgery', '$4,000 - $7,000', ARRAY['English', 'Spanish'], ARRAY['Bariatric Center of Excellence', 'US Border'], 'Within 3 months', '{"phone": "+52 664 123 4567", "email": "info@tijuanamedical.com", "website": "https://www.tijuanamedical.com"}', ARRAY['Gastric Sleeve', 'Gastric Bypass', 'Lap Band'], '[{"source": "Obesity Help", "url": "https://www.obesityhelp.com/example", "score": "4.5/5"}]', null);
