-- Clear existing data and insert comprehensive sample data
DELETE FROM providers;

INSERT INTO providers (id, name, location, procedure, priceRange, languages, tags, availability, contact, services, reviews, mapEmbedUrl)
VALUES
-- Hair Transplant Clinics
('1', 'Istanbul Elite Hair Center', '{"city": "Istanbul", "country": "Turkey", "address": "Nisantasi Plaza, Tesvikiye Cad. No:12, Sisli"}', 'Hair Transplant', '$2,800 - $4,500', ARRAY['English', 'Turkish', 'Arabic', 'German'], ARRAY['JCI Accredited', 'Airport pickup', 'Accommodation', 'Follow-up care'], 'Next 2 weeks', '{"phone": "+90 212 555 0123", "email": "info@istanbulelitehair.com", "website": "https://www.istanbulelitehair.com"}', ARRAY['FUE Hair Transplant', 'DHI Hair Transplant', 'Beard Transplant', 'Eyebrow Transplant'], '[{"source": "Trustpilot", "url": "https://www.trustpilot.com/review/istanbulelitehair.com", "score": "4.8"}, {"source": "Google", "url": "https://maps.app.goo.gl/example1", "score": "4.7"}]', null),

('2', 'Antalya Hair Solutions', '{"city": "Antalya", "country": "Turkey", "address": "Lara Beach Resort Area, Kundu Mah."}', 'Hair Transplant', '$2,200 - $3,800', ARRAY['English', 'Turkish', 'Russian'], ARRAY['ISO Certified', 'Airport pickup', 'Accommodation'], 'Within 1 month', '{"phone": "+90 242 555 0456", "email": "contact@antalyahair.com", "website": "https://www.antalyahair.com"}', ARRAY['FUE Hair Transplant', 'Sapphire FUE', 'DHI Method'], '[{"source": "Google", "url": "https://maps.app.goo.gl/example2", "score": "4.6"}]', null),

-- Dental Clinics
('3', 'Bangkok Smile Dental Center', '{"city": "Bangkok", "country": "Thailand", "address": "Central World, 999/9 Rama I Road, Pathumwan"}', 'Dental Implants', '$1,200 - $2,500', ARRAY['English', 'Thai', 'Chinese'], ARRAY['JCI Accredited', 'Airport pickup', 'Translator service'], 'Within 2 weeks', '{"phone": "+66 2 555 7890", "email": "info@bangkoksmile.com", "website": "https://www.bangkoksmile.com"}', ARRAY['Dental Implants', 'All-on-4', 'Veneers', 'Teeth Whitening', 'Root Canal'], '[{"source": "Google", "url": "https://maps.app.goo.gl/example3", "score": "4.9"}, {"source": "Facebook", "url": "https://facebook.com/bangkoksmile", "score": "4.8"}]', null),

('4', 'Phuket Dental Paradise', '{"city": "Phuket", "country": "Thailand", "address": "Patong Beach Road, Kathu District"}', 'Dental Implants', '$900 - $2,000', ARRAY['English', 'Thai', 'German'], ARRAY['ISO Certified', 'Airport pickup', 'Accommodation'], 'Flexible', '{"phone": "+66 76 555 1234", "email": "care@phuketdental.com", "website": "https://www.phuketdental.com"}', ARRAY['Dental Implants', 'Crowns & Bridges', 'Orthodontics', 'Cosmetic Dentistry'], '[{"source": "TripAdvisor", "url": "https://tripadvisor.com/phuketdental", "score": "4.7"}]', null),

-- Cosmetic Surgery
('5', 'Seoul Beauty Medical Center', '{"city": "Seoul", "country": "South Korea", "address": "Gangnam-gu, Apgujeong-ro 123"}', 'Cosmetic Surgery', '$3,500 - $12,000', ARRAY['English', 'Korean', 'Chinese'], ARRAY['JCI Accredited', 'Translator service', 'Follow-up care'], 'Within 1 month', '{"phone": "+82 2 555 9876", "email": "international@seoulbeauty.com", "website": "https://www.seoulbeauty.com"}', ARRAY['Rhinoplasty', 'Double Eyelid Surgery', 'Facelift', 'Breast Augmentation', 'Liposuction'], '[{"source": "RealSelf", "url": "https://www.realself.com/seoulbeauty", "score": "4.9"}, {"source": "Google", "url": "https://maps.app.goo.gl/example5", "score": "4.8"}]', null),

('6', 'Busan Aesthetic Institute', '{"city": "Busan", "country": "South Korea", "address": "Haeundae-gu, Marine City"}', 'Cosmetic Surgery', '$2,800 - $9,500', ARRAY['English', 'Korean', 'Japanese'], ARRAY['ISO Certified', 'Airport pickup', 'Translator service'], 'Within 3 months', '{"phone": "+82 51 555 4567", "email": "info@busanaesthetic.com", "website": "https://www.busanaesthetic.com"}', ARRAY['Facial Contouring', 'Breast Surgery', 'Body Contouring', 'Anti-aging Treatments'], '[{"source": "Google", "url": "https://maps.app.goo.gl/example6", "score": "4.6"}]', null),

-- Eye Surgery
('7', 'Mumbai Vision Excellence', '{"city": "Mumbai", "country": "India", "address": "Bandra Kurla Complex, G Block"}', 'Eye Surgery (LASIK)', '$800 - $1,800', ARRAY['English', 'Hindi', 'Marathi'], ARRAY['NABH Accredited', 'Follow-up care', 'Airport pickup'], 'Next 2 weeks', '{"phone": "+91 22 555 3456", "email": "care@mumbaivision.com", "website": "https://www.mumbaivision.com"}', ARRAY['LASIK', 'PRK', 'Cataract Surgery', 'Retinal Surgery', 'Glaucoma Treatment'], '[{"source": "Practo", "url": "https://www.practo.com/mumbaivision", "score": "4.8"}, {"source": "Google", "url": "https://maps.app.goo.gl/example7", "score": "4.7"}]', null),

('8', 'Delhi Eye Care Center', '{"city": "New Delhi", "country": "India", "address": "Connaught Place, Central Delhi"}', 'Eye Surgery (LASIK)', '$600 - $1,500', ARRAY['English', 'Hindi', 'Punjabi'], ARRAY['NABH Accredited', 'Airport pickup'], 'Within 1 month', '{"phone": "+91 11 555 7890", "email": "info@delhieyecare.com", "website": "https://www.delhieyecare.com"}', ARRAY['LASIK', 'SMILE', 'ICL', 'Cataract Surgery'], '[{"source": "Google", "url": "https://maps.app.goo.gl/example8", "score": "4.5"}]', null),

-- Weight Loss Surgery
('9', 'Tijuana Bariatric Excellence', '{"city": "Tijuana", "country": "Mexico", "address": "Zona Rio, Paseo de los Heroes 9350"}', 'Weight Loss Surgery', '$4,500 - $8,500', ARRAY['English', 'Spanish'], ARRAY['Bariatric Center of Excellence', 'Airport pickup', 'Follow-up care'], 'Within 2 weeks', '{"phone": "+52 664 555 2468", "email": "info@tijuanabariatric.com", "website": "https://www.tijuanabariatric.com"}', ARRAY['Gastric Sleeve', 'Gastric Bypass', 'Duodenal Switch', 'Revision Surgery'], '[{"source": "Obesity Help", "url": "https://www.obesityhelp.com/tijuanabariatric", "score": "4.7"}, {"source": "Google", "url": "https://maps.app.goo.gl/example9", "score": "4.6"}]', null),

('10', 'Cancun Weight Loss Center', '{"city": "Cancun", "country": "Mexico", "address": "Hotel Zone, Blvd. Kukulcan Km 8.5"}', 'Weight Loss Surgery', '$5,200 - $9,800', ARRAY['English', 'Spanish'], ARRAY['JCI Accredited', 'Airport pickup', 'Accommodation'], 'Flexible', '{"phone": "+52 998 555 1357", "email": "care@cancunweightloss.com", "website": "https://www.cancunweightloss.com"}', ARRAY['Gastric Sleeve', 'Gastric Bypass', 'Gastric Band', 'Mini Gastric Bypass'], '[{"source": "Bariatric Surgery Source", "url": "https://bariatricsurgerysource.com/cancun", "score": "4.8"}]', null),

-- Orthopedic Surgery
('11', 'Bangkok Orthopedic Hospital', '{"city": "Bangkok", "country": "Thailand", "address": "Silom Road, Bang Rak District"}', 'Knee Replacement', '$8,500 - $15,000', ARRAY['English', 'Thai'], ARRAY['JCI Accredited', 'Airport pickup', 'Follow-up care'], 'Within 1 month', '{"phone": "+66 2 555 4680", "email": "international@bangkokortho.com", "website": "https://www.bangkokortho.com"}', ARRAY['Total Knee Replacement', 'Hip Replacement', 'Shoulder Surgery', 'Spine Surgery'], '[{"source": "Google", "url": "https://maps.app.goo.gl/example11", "score": "4.7"}]', null),

('12', 'Prague Orthopedic Institute', '{"city": "Prague", "country": "Czech Republic", "address": "Wenceslas Square, New Town"}', 'Knee Replacement', '$12,000 - $18,000', ARRAY['English', 'Czech', 'German'], ARRAY['ISO Certified', 'Airport pickup', 'Translator service'], 'Within 3 months', '{"phone": "+420 224 555 789", "email": "info@pragueortho.com", "website": "https://www.pragueortho.com"}', ARRAY['Knee Replacement', 'Hip Replacement', 'Sports Medicine', 'Arthroscopy'], '[{"source": "Google", "url": "https://maps.app.goo.gl/example12", "score": "4.6"}]', null),

-- Fertility Treatment
('13', 'Athens Fertility Center', '{"city": "Athens", "country": "Greece", "address": "Kolonaki Square, Central Athens"}', 'Fertility Treatment', '$3,500 - $8,000', ARRAY['English', 'Greek', 'German'], ARRAY['ISO Certified', 'Airport pickup', 'Translator service'], 'Within 2 weeks', '{"phone": "+30 210 555 3691", "email": "info@athensfertility.com", "website": "https://www.athensfertility.com"}', ARRAY['IVF', 'ICSI', 'Egg Donation', 'Surrogacy', 'Genetic Testing'], '[{"source": "FertilityIQ", "url": "https://www.fertilityiq.com/athens", "score": "4.8"}]', null),

('14', 'Cyprus IVF Centre', '{"city": "Nicosia", "country": "Cyprus", "address": "Ledra Street, Old City"}', 'Fertility Treatment', '$2,800 - $6,500', ARRAY['English', 'Greek', 'Turkish'], ARRAY['JCI Accredited', 'Airport pickup', 'Follow-up care'], 'Flexible', '{"phone": "+357 22 555 147", "email": "care@cyprusivf.com", "website": "https://www.cyprusivf.com"}', ARRAY['IVF', 'Egg Donation', 'Sperm Donation', 'Embryo Donation', 'PGD'], '[{"source": "Google", "url": "https://maps.app.goo.gl/example14", "score": "4.9"}]', null),

-- Cancer Treatment
('15', 'Singapore Oncology Institute', '{"city": "Singapore", "country": "Singapore", "address": "Orchard Road, Central Singapore"}', 'Cancer Treatment', '$15,000 - $80,000', ARRAY['English', 'Mandarin', 'Malay'], ARRAY['JCI Accredited', 'Airport pickup', 'Translator service', 'Follow-up care'], 'Within 1 month', '{"phone": "+65 6555 7890", "email": "international@singaporeoncology.com", "website": "https://www.singaporeoncology.com"}', ARRAY['Chemotherapy', 'Radiation Therapy', 'Immunotherapy', 'Surgical Oncology', 'Precision Medicine'], '[{"source": "Google", "url": "https://maps.app.goo.gl/example15", "score": "4.9"}, {"source": "HealthHub", "url": "https://healthhub.sg/singaporeoncology", "score": "4.8"}]', null);
